---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd({path-to-dir})
source("utils_microglia_IVSM.R")
```

# Initiate environment
```{r}
microglia <- new.env()
attr(microglia, "name") <- "microglia"
```

# Load and process data
```{r}
microglia <- process.enh.cDNA.plasmid(env = microglia, 
                                      line = "BV2_sample_1", 
                                      plasmid.counts.file.path = {path-to-plasmid-counts},
                                      min.plasmid.bcs = 4,
                                      cDNA.counts.file.path = {path-to-cdna-counts}, 
                                      min.cDNA.bcs = 4, 
                                      out.dir = {path-to-output})
```

```{r}
microglia <- process.enh.cDNA.plasmid(env = microglia, 
                                      line = "BV2_sample_2", 
                                      plasmid.counts.file.path = {path-to-plasmid-counts},
                                      min.plasmid.bcs = 4,
                                      cDNA.counts.file.path = {path-to-cdna-counts}, 
                                      min.cDNA.bcs = 4, 
                                      out.dir = {path-to-output})
```

```{r}
microglia <- process.enh.cDNA.plasmid(env = microglia, 
                                      line = "BV2_sample_3", 
                                      plasmid.counts.file.path = {path-to-plasmid-counts},
                                      min.plasmid.bcs = 4,
                                      cDNA.counts.file.path = {path-to-cdna-counts}, 
                                      min.cDNA.bcs = 4, 
                                      out.dir = {path-to-output})
```

```{r}
saveRDS(object = microglia, file = "{path-to-output}/microglia_env.rds")
```

################

```{r}
microglia <- readRDS(file = "{path-to-output}/microglia_env.rds")
```

# Generate table for DEseq
```{r}
library(dplyr)
raw_table_BV2 <- inner_join(x = microglia$`BV2_sample_1`$merged[,c("synthetic.region", "counts.plasmid", "counts.cDNA")], y = microglia$`BV2_sample_2`$merged[,c("synthetic.region", "counts.plasmid", "counts.cDNA")], by = "synthetic.region", suffix = c(".R1", ".R2"))
raw_table_BV2 <- inner_join(x = raw_table_BV2, y = microglia$`BV2_sample_3`$merged[,c("synthetic.region", "counts.plasmid", "counts.cDNA")], by = "synthetic.region")
names(raw_table_BV2)[2:7] <- c("microglia_BV2_R1_Plasmid", "microglia_BV2_R1_cDNA", "microglia_BV2_R2_Plasmid", "microglia_BV2_R2_cDNA", "microglia_BV2_R3_Plasmid", "microglia_BV2_R3_cDNA")
raw_table_BV2 <- as.data.frame(raw_table_BV2)
row.names(raw_table_BV2) <- raw_table_BV2[,1]
raw_table_BV2 <- raw_table_BV2[,-1]
saveRDS(raw_table_BV2, '{path-to-output}/raw_counts_table.BV2new.RDS')
```

# DEseq
```{r}
library(DESeq2)
raw_table_BV2 <- readRDS('{path-to-output}/raw_counts_table.BV2new.RDS')
timepoints <- c('BV2')
plasmid_class <- c('microglia')
timepoints_sample <- sapply(strsplit(colnames(raw_table_BV2), split = "_"), "[", 2)
plasmid_sample <- sapply(strsplit(colnames(raw_table_BV2), split = "_"), "[", 1)
res_list <- list()
res_list_filt <- list()
for (time in timepoints){
  for (plasmid in plasmid_class){
      sub_raw_counts <- raw_table_BV2[,which(timepoints_sample == time)]
      plasmid_sample <- sapply(strsplit(colnames(sub_raw_counts), split = "_"), "[", 1)
      if (sum(plasmid_sample == plasmid) > 0){
        sub_raw_counts <- sub_raw_counts[,which(plasmid_sample == plasmid)]
      
        samples <- sort(colnames(sub_raw_counts))
        coldata <- sapply(strsplit(samples, split = "_"), "[", 4)
        names(coldata) <- samples
        coldata <- as.data.frame(coldata)
        colnames(coldata) <- 'condition'
        print(coldata)
        if (length(samples) == 2){
          dds <- DESeqDataSetFromMatrix(countData = sub_raw_counts,
                                    colData = coldata[colnames(sub_raw_counts),,drop=FALSE],
                                    design = ~ 1)
        } else{
          dds <- DESeqDataSetFromMatrix(countData = sub_raw_counts,
                                    colData = coldata[colnames(sub_raw_counts),,drop=FALSE],
                                    design = ~ condition)
          dds$condition <- relevel(dds$condition, ref = "Plasmid")
        }

        dds <- DESeq(dds)
        res <- results(dds)
        cc_res <- res[complete.cases(res),]
        res_list[[paste0(plasmid, '_', time)]] <- cc_res
        print(dim(cc_res))
        res_list_filt[[paste0(plasmid, '_', time)]] <- cc_res[which(cc_res$padj < 0.1),]
        print(dim(cc_res[which(cc_res$padj < 0.1),]))
      }
  }
}

saveRDS(res_list, '{path-to-output}/DESEQ_BV2new_results_no_prefilter.Rds')
saveRDS(res_list_filt, '{path-to-output}/DESEQ_BV2new_results_no_prefilter_01.Rds')
```

```{r}
res_list <- readRDS('{path-to-output}/DESEQ_BV2new_results_no_prefilter.Rds')

vd_list <- list()
for (slot in names(res_list)){
  res_info <- res_list[[slot]]
  data <- as.data.frame(cbind(rownames(res_info),res_info[rownames(res_info),'log2FoldChange', drop=FALSE], rep(slot, nrow(res_info))))
  colnames(data) <- c('Region','LogFC', 'Condition')
  vd_list[[slot]] <- data
}
library(data.table)
violin_data_bv2 <- rbindlist(vd_list)
```

# Expression per class
```{r}
library(ggplot2)
library(stringr)
violin_data_bv2$name <- str_sub(string = violin_data_bv2$Region, 1, -14)
violin_data_bv2$Class <- "NA"
violin_data_bv2[grep(pattern = "FIRE-ST",violin_data_bv2$name),"Class"] <- "FIRE_SM"
violin_data_bv2[grep(pattern = "Shuffle_",violin_data_bv2$name),"Class"] <- "Shuffled"
ggplot(violin_data_bv2, aes(x=Class, y=LogFC, fill=Class)) +
  geom_boxplot() + 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 7))
```

# Define active enhancers (Gaussian fit)
```{r}
library(ggplot2)
library(robustbase)
library(stats)

sample <- violin_data_bv2
subsettype <- "Shuffled"

# robust fit of a gaussian by robust estimates of it's two parameters
## Use median
location <- median(x = sample[sample$Class == subsettype,]$LogFC)
print(paste0("Median: ",location))
## Use max density value
scale <- mad(x = sample[sample$Class == subsettype,]$LogFC)

# Check fit
p2 <- ggplot(data = sample, mapping = aes(x = LogFC, fill = Class)) +
        geom_density(size = 0, alpha = .5) +  
        stat_function(fun = dnorm, args = list(mean = location, sd = scale)) + 
        theme_minimal() +
        labs(title = "microglia")
print(p2)

# Determine p-values for all
sample$pvalue <- pnorm(q = sample$LogFC, mean = location, sd = scale, lower.tail = F)
sample$padj <- p.adjust(p = sample$pvalue, method = "fdr")

p3 <- ggplot(data = sample, mapping = aes(x = padj < 0.05, fill = Class)) + 
        geom_bar() +
        theme_minimal() +
        labs(title = "microglia")
print(p3)

p <- ggplot(sample, aes(x = padj, y = LogFC, fill = Class)) +
  geom_point(pch = 21, size = 3) +
  geom_vline(xintercept = 0.05, linetype="dashed", color = "black", size = 0.5) +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_text(color = "black", size = 7),
        axis.title = element_text(size = 8),
        legend.key = element_blank(),
        legend.title = element_text(size = 7),
        legend.text = element_text(size = 7),
        legend.key.size = unit(0.8,"line")) +
  labs(x = "Adjusted p-value", y = "Log2 Expression", color = "Adjusted\np-value", fill = "Class")
print(p)

# Get stats
print("Proportions of active tiles:")
print(table(sample[sample$padj < 0.05, "Class"])/sum(sample$padj < 0.05)*100)
print(paste0("Percentage of active shuffled: ", nrow(sample[sample$padj < 0.05 & sample$Class == "Shuffled",])/nrow(sample[sample$Class == "Shuffled",])*100, "%"))
print(paste0("Number of active tiles: ",nrow(sample[sample$padj < 0.05,])))
print("")

# Save results
violin_data_bv2 <- sample
```

# Generate fold change over WT for ploting with DeepExplainer (FIRE SM)

```{r}
fire.deseq <- violin_data_bv2[violin_data_bv2$Class == "FIRE_SM",]
fire.deseq$Region <- paste0(str_split(string = fire.deseq$Region, pattern = "_",simplify = T)[,5],"_",str_split(string = fire.deseq$Region, pattern = "_",simplify = T)[,4])
fire.deseq <- fire.deseq[,c("Region", "LogFC")]
write.table(x = fire.deseq, file = "{path-to-output}/FIRE_SM_DEseq_BV2new.tsv", sep = "\t", row.names = F, quote = F)
```
